info:
  app:
    name: Serviço Treinamento Service BUS - Sender

spring:
  profiles:
    active: local

management:
  endpoint:
    health:
      show-details: "ALWAYS"
      status:
        http-mapping:
          UP: 200
          UNKNOWN: 200
          DOWN: 200
          OUT_OF_SERVICE: 200
  endpoints:
    web:
      base-path: /
      exposure:
        include: health,info,metrics
        exclude:

